name: David Gwynn
analytics: {}
content_rating:
  adult: false
github: true
description: personal information on David Gwynn
opengraph: {}
title: David Gwynn personal site
author: {}
color:
  lightness: 0.10358924747062596
  brandColors:
    - '#FF8000'
    - '#FFD933'
    - '#CCCC52'
    - '#8FB359'
    - '#192B33'
  saturation: 0.4429437907978296
  brandStrength: 0.28268589900869084
  rhythmicContrast: 0.9054360296357041
